#!/bin/bash

echo "### SECRETS OF ORDERER ###"
pushd ./channel-artifacts/
set -x
kubectl create secret generic genesis-block --from-file=genesis=genesis.block
set +x
popd

pushd ./certs/ordererorg/orderer/msp/
set -x
kubectl create secret generic orderer-msp --from-file=config=config.yaml --from-file=cacerts=cacerts/35-187-18-11-7054.pem --from-file=keystore=keystore/*_sk --from-file=signcerts=signcerts/cert.pem
set +x
popd

pushd ./certs/ordererorg/orderer/tls/
set -x
kubectl create secret generic orderer-tls --from-file=ca=ca.crt --from-file=server-cert=server.crt --from-file=server-key=server.key
set +x
popd

echo "### SECRETS OF PEER ###"
pushd ./certs/peerorg/peer/msp
set -x
kubectl create secret generic peer-msp --from-file=config=config.yaml --from-file=cacerts=cacerts/35-233-46-15-7054.pem --from-file=keystore=keystore/*_sk --from-file=signcerts=signcerts/cert.pem
set +x
popd

pushd ./certs/peerorg/peer/tls
set -x 
kubectl create secret generic peer-tls --from-file=ca=ca.crt --from-file=server-cert=server.crt --from-file=server-key=server.key
set +x
popd