#!/bin/bash

#orderer
kubectl create secret generic genesis-block --from-file=genesis=genesis.block

kubectl create secret generic orderer-msp --from-file=config=config.yaml --from-file=cacerts=cacerts/35-187-18-11-7054.pem --from-file=keystore=keystore/a213026961077a617b25bdf87762304232d8c5a4042895e7383238d81ba75c38_sk --from-file=signcerts=signcerts/cert.pem

kubectl create secret generic orderer-tls --from-file=ca=ca.crt --from-file=server-cert=server.crt --from-file=server-key=server.key

# peer
kubectl create secret generic peer-msp --from-file=config=config.yaml --from-file=cacerts=cacerts/35-233-46-15-7054.pem --from-file=keystore=keystore/e48456d710b79ee14e68c414c2f8e0ce93701837f776d9d01d44b8dc33eff1cb_sk --from-file=signcerts=signcerts/cert.pem

kubectl create secret generic peer-tls --from-file=ca=ca.crt --from-file=server-cert=server.crt --from-file=server-key=server.key